name = "Comfortable Basic"
license = "MIT"
licenselink = "https://github.com/freemagee/comfortable-basic/blob/master/LICENSE.md"
description = "Comfortable Basic Hugo theme for simple blogging"
homepage = "http://neilmagee.com"
tags = ["blog"]
features = []
min_version=0.43

[author]
  name = "Neil Magee"
  homepage = "http://neilmagee.com"

[original]
  name = "Comfortable Basic"
  homepage = "https://github.com/freemagee/comfortable-basic"
  repo = "https://github.com/freemagee/comfortable-basic"
